#!/bin/bash

# `crunch <file-or-directory>`

# 0=true
# 1=false

_isTar() {
	untarred="${1%\.tar*}"
	if [[ "${1}" == "${untarred}" ]] ; then
		echo 1
		return #false
	fi
	echo 0
	return #true
}

_tarMe() {
	echo "  tar -cf ${1} ${2}"
	tar -cf "${1}" "${2}"
}

_xzMe() {
	echo "  xz -zv -T 0 -e9 ${1}"
	xz -zv -T 0 -e9 "${1}"
}

# If user passed more than one argument: 
if [ -n "${2}" ] ; then
	toCrunch="crunch-nec.tar" ;
	_tarMe "${toCrunch}" "$@" ;
	tempTar=true ;

# Else if the passed argument is not already tarred:
elif [[ $(_isTar "${1}") == 1 ]] ; then
	toCrunch="${1}.tar" ;
	_tarMe "${toCrunch}" "${1}" ;
	tempTar=true ;

# Otherwise:
else
	toCrunch="${1}" ;

fi ;

_xzMe "${toCrunch}" ;
